src/parser.rs

This PR works on a TODO and introduces changes to `get_syntax()` to use the `content-type` header when available and falls back to using the extension to determine the syntax of the content.

Use content-type header to determine syntax

---

src/graph.rs
src/loader.rs
src/parser.rs

This commit changes how pure JS files are stored in the bundle. They are
no longer transpiled. Instead the `transpiled` field is now an `Option`,
and for JS files this `Option` is `None`. After the change old zips will
work with the new loader, but the old loader will not work with new
zips.

chore: reduce bundle size use for js files

---

Cargo.lock
Cargo.toml
src/error.rs
src/loader.rs

This PR introduces data URL support.
```
➜  cargo run --example fetch data:text/javascript\;base64,Y29uc29sZS5sb2coJ2hpJyk7
Finished dev [unoptimized + debuginfo] target(s) in 0.13s
Running `target/debug/examples/fetch 'data:text/javascript;base64,Y29uc29sZS5sb2coJ2hpJyk7'`
1/1   data:text/javascript;base64,Y29uc29sZS5sb2coJ2hpJyk7
{
"version": 1,
"modules": {
"data:text/javascript;base64,Y29uc29sZS5sb2coJ2hpJyk7": {
"Source": {
"source": "console.log('hi');",
"transpiled": null,
"content_type": "text/javascript",
"deps": []
}
}
}
}
```
It also introduces changes to an error on unsupported schemes like `file:`.

feat: support data URLs

---

Cargo.lock
Cargo.toml
src/parser.rs

Use `deno_ast` crate instead of swc crates directly.  This should make it easier to keep swc updated.

refactor: use `deno_ast` crate

---

src/parser.rs

It was previously incorrectly emitting like so:
```ts
export class EventEmitter {
static  #init() {
}
}
EventEmitter.call = function call(thisArg) {
EventEmitter.#init(thisArg);
};
```
Fixes:
```
Uncaught SyntaxError: Private field '#init' must be declared in an enclosing class
at https://deno.land/std@0.113.0/node/events.ts:493:16
```

fix: enable use_define_for_class_fields

---

lib/eszip.ts

A first pass at a small "swiss army knife" for ESZIPs with the following subcommands:
-`l`/`ls`/`list`: lists specifiers (without extracting)
-`x`/`extract`: extracts to a directory of the user's choice
-`r`/`run`: extracts to a tmp dir, runs `deno` with an import map then cleans up the tmp dir
- Use `deno vendor` logic for more robust extraction
- Limit permissions of run
- Print out module graph/tree vs list
- Warn of dangling/missing specifiers
- Rewrite in Rust ? (easier to reuse vendoring, graph tooling, etc...)

feat: first iteration of an eszip CLI

---

lib/eszip.ts
lib/eszip_wasm.generated.js

Also updates `eszip run` to use `--no-check` by default since the graph contains transpiled modules and type checking is pointless.

tool: Add `eszip build` subcommand

---

lib/loader.ts

While browsing through some code, VSCode showed me this comment with a copy&paste typo. Here's a fix :)

chore: fix typo in loader.ts

---

src/testdata/source/import_import_map.js
src/v2.rs

This commit ensures that one import map appears just once in the generated eszip.
Fixes #110 
Now a generated eszip works fine with eszip_builder and eszip_viewer.
```sh
$ cargo run --example eszip_builder file://$(pwd)/main.js out.eszip file://$(pwd)/import_map.json
source: file:///Users/yusuktan/Repo/github.com/magurotuna/eszip/import_map.json
source: file:///Users/yusuktan/Repo/github.com/magurotuna/eszip/main.js
```
```sh
$ cargo run --example eszip_viewer out.eszip
Specifier: file:///Users/yusuktan/Repo/github.com/magurotuna/eszip/import_map.json
Kind: Json
---
{
"imports": {
}
}
---
============
Specifier: file:///Users/yusuktan/Repo/github.com/magurotuna/eszip/main.js
Kind: JavaScript
---
import m from "./import_map.json" assert { type: "json" };
---
============
```

fix: avoid including duplicate import map if it's imported from program

---

rust-toolchain.toml
src/testdata/emit/dynamic.ts
src/testdata/source/dynamic.ts
src/v2.rs

This commit fixes a case where dynamically importing a specifier that
resolves, but does not load (ie a relative specifier pointing to
nowhere), would cause the EszipV2::from_graph process to fail.
This commit fixes this behaviour by ignoring load errors for modules
only imported via dynamic import.

fix: don't fail build on dynamic import load error

---

Cargo.lock
Cargo.toml
lib/lib.rs
src/examples/builder.rs
src/lib.rs
src/testdata/deno_jsonc_as_import_map/a.ts
src/testdata/deno_jsonc_as_import_map/deno.jsonc
src/testdata/deno_jsonc_as_import_map/main.ts
src/v1.rs
src/v2.rs

This commit allows JSONC to be embedded in an eszip as an import map. This is primarily for deno's config file, which can be JSONC (e.g. `deno.jsonc`).
Embedded JSONC data can then be retrieved by calling `get_import_map` method, which is a new method. Keep in mind that the existing similar method, `get_module`, will not return JSONC. This separation ensures that whatever returned from `get_module` is definitely a valid module, which may be useful when implementing support for dynamic import.
Ideally eszip's serialization format should have a dedicated optional section for an import map so that we can treat import maps and modules differently. We can't do this while keeping v2 since this would break backward compatibility.
ref https://github.com/denoland/deploy_feedback/issues/344
ref …

feat: allow JSONC to be embedded as an import map

---

lib/lib.rs
src/examples/builder.rs
src/lib.rs
src/v1.rs
src/v2.rs

This removes a double boxing, and allows zero-copy loading into
deno_core through `FastString::Arc`.

chore: use Arc<[u8]> instead of Arc<Vec<u8>>

---

Cargo.lock

Fixes: `webpki: CPU denial of service in certificate path building`

chore: cargo update to fix webpki vuln warning

---

rust-toolchain.toml
src/lib.rs
src/v1.rs
src/v2.rs

This adds implementation of `IntoIterator` trait for `Eszip` and `EszipV1`. This will help us iterate over all the modules included in an eszip archive.
Note that we have already `IntoIterator` implemented for `EszipV2`.

feat: implement `IntoIterator` for `Eszip` and `EszipV1`

---

src/lib.rs
src/v2.rs

`BufReader` does not guarantee that `buffer().len() >= 8`, which is the length of the V2 magic. Particularly when using `IntoAsyncRead`, the buffer is the first `AsRef<[u8]>` item in the wrapped stream, regardless of its size, failing to parse if the slice length is smaller than 8 bytes.

Fix: parsing from `IntoAsyncRead` with small chunks

---

Cargo.lock
Cargo.toml

Accidentally missed this in https://github.com/denoland/eszip/pull/186

fix: bump deno_npm to 0.21

---

Cargo.lock
Cargo.toml
benches/source_hash_function.rs
lib/lib.rs
src/examples/builder.rs
src/lib.rs
src/v2.rs

This is for `deno compile`.
1. It allows us to not mix windows paths on linux and vice versa.
1. We won't be storing the build machine's folder path in the binary anymore.
1. It makes workspace support easier to implement because I can lay out the files in the eszip in the same directory as the node_modules folder. It's not really easy to do this otherwise.
That said, there is a drawbacks that if someone is using an absolute file path in an import specifier then it will no longer work if the path is within the folder to make everything relative to.
Let me know if you think of a better solution, but I feel like this is reasonable?

feat: `from_graph` - ability to make file specifiers relative

---

Cargo.lock
Cargo.toml
benches/source_hash_function.rs
lib/lib.rs
src/examples/builder.rs
src/testdata/source/child1.ts
src/testdata/source/child2.ts
src/testdata/source/grandchild1.ts
src/testdata/source/grandchild2.ts
src/testdata/source/npm_imports_main.ts
src/testdata/source/npm_imports_submodule.ts
src/testdata/source/parent.ts
src/v2.rs

This is a draft implementation of the support for including npm packages in the eszip, honoring the ModuleGraph order. 
This PR also fixes the ordering of the modules within the eszip, which was DPS instead of BFS
Before landing this PR, the deno_node and deno_fs dependencies need to be removed.
Also note that this PR is based on 0.72.1 for testing convenience. Will rebase before getting ready to review

feat: Support adding npm packages to the eszip

---

src/v2.rs

This new method is a generalization of `add_import_map()`. Can be used to add any module to the front of the eszip, like for example a serialized `deno_config::resolver::WorkspaceResolver`

feat: `EszipV2::add_to_front()`

---

src/examples/viewer.rs

This PR introduces a flag --output to extract the eszip into a directory of files for easy navigation and readability of source code.
```
Usage:
viewer <eszip_path>
viewer --output <output_dir> <eszip_path>
viewer -o <output_dir> <eszip_path>
```

feat(examples/viewer): add --output flag to extract eszip to dir

---

Cargo.lock
Cargo.toml
src/v2.rs

* https://github.com/denoland/deno_graph/pull/540
Analyzes `require` calls and parses with `parse_program` instead of `parse_module`.

refactor: deno_graph 0.84
